USE copycat;

INSERT INTO products(name, short_description, long_description, price, img, createdAt, updatedAt)
VALUES ("Siberian Kitten", "Friendly and adventurous", "The Siberian is a centuries-old landrace of domestic cat in Russia and recently developed as a formal breed with standards promulgated the world over since the late 1980s. Siberians vary from medium to medium-large in size.", 2500.00, "/assets/images/cat_type_01th.jpg", "2020-10-18","2020-10-18" ),
("Abyssinian Kitten", "Loving and affectionate!","The Abyssinian is a breed of domestic short-haired cat with a distinctive tabby coat, in which individual hairs are banded with different colors. In nomenclature terms, they are also known as simply Abys. The breed is named for Abyssinia, where it is believed to have originated.", 2000.00, "/assets/images/cat_type_02th.jpg", "2020-10-18","2020-10-18" ),
("Burmese Kitten", "Extremely friendly and affectionate", "The Burmese cat is a breed of domestic cat, originating in Burma, believed to have its roots near the Thai-Burma border and developed in the United States and Britain. Most modern Burmese are descendants of one female cat called Wong Mau, which was brought from Burma to America in 1930 and bred with American Siamese.", 2500.00, "/assets/images/cat_type_03th.jpg", "2020-10-18","2020-10-18" ),
("Norwegian Forest Cat Kitten", "Sweet and gentle", "The Norwegian Forest cat is a breed of domestic cat originating in Northern Europe. This natural breed is adapted to a very cold climate, with a top coat of glossy, long, water-shedding hair and a woolly undercoat for insulation.", 3500.00, "/assets/images/cat_type_04th.jpg", "2020-10-18","2020-10-18" ),
("American Shorthair Kitten", "Friendly, playful, and accepting", "The American Shorthair is a breed of domestic cat believed to be descended from European cats brought to North America by early settlers to protect valuable cargo from mice and rats. According to the Cat Fanciers' Association, in 2012, it was the seventh most popular pedigreed cat in the United States.", 5000.00, "/assets/images/cat_type_05th.jpg", "2020-10-18","2020-10-18" ),
("Ragdoll Kitten", "Gentle, calm and sociable!" ,"The Ragdoll is a cat breed with a color point coat and blue eyes. They are large and muscular semi-longhair cats with a soft and silky coat. Developed by American breeder Ann Baker in the 1960s, they are best known for their docile and placid temperament and affectionate nature.", 7500.00, "/assets/images/cat_type_06th.jpg", "2020-10-18","2020-10-18" ),
("Maine Coon Kitten", "Sweet tempered and gentle","The Maine Coon is the largest domesticated cat breed. It has a distinctive physical appearance and valuable hunting skills. It is one of the oldest natural breeds in North America, specifically native to the US state of Maine, where it is the official state cat.", 10000.00, "/assets/images/cat_type_07th.jpg", "2020-10-18", "2020-10-18");